FROM python:3.11-slim

ENV PYTHONIOENCODING=UTF-8
ENV LANG=C.UTF-8

WORKDIR /app

# requirements zuerst für besseren Caching-Effekt
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# App-Code kopieren
COPY weather_producer.py /app/weather_producer.py

CMD ["python", "weather_producer.py"]