{
 "title": "OpenWeatherMap-Big-Data-Project3",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Event Count, Avg Lag (event → processing) & Anomaly Count (per processing_time) - last 20 events",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH latest AS (\n  SELECT\n    to_timestamp(processing_time) AS time,\n    COUNT(*) AS event_count,\n    AVG(processing_time - event_time) AS avg_lag_seconds,\n    COUNT(*) FILTER (WHERE anomaly = true) AS anomaly_count\n  FROM weather_data\n  GROUP BY time\n  ORDER BY time DESC\n  LIMIT 20\n)\nSELECT * FROM latest\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Ingestion Lag and Anomaly Status per City (Event vs. Processing Timestamps) last 20 events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  city,\n  processing_time - event_time AS lag_event_to_processing_seconds,\n  processing_time - received_time AS lag_received_to_processing_seconds,\n  to_timestamp(event_time) AS event_time,\n  to_timestamp(received_time) AS received_time,\n  to_timestamp(processing_time) AS processing_time,\n  anomaly\nFROM weather_data\nORDER BY processing_time DESC\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Event Time vs Processing Time - last 20 minutes",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  to_timestamp(event_time) AS event_time,\n  to_timestamp(processing_time) AS processing_time\nFROM\n  weather_data\nWHERE\n  to_timestamp(processing_time) > now() - interval '20 minutes'\nORDER BY\n  processing_time;"
    }
   ]
  },
  {
   "title": "Total anomaly Frequency by City and Weather Conditions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  city,\n  temperature,\n  wind_speed,\n  humidity,\n  pressure,\n  COUNT(*) AS anomaly_count\nFROM\n  weather_data\nWHERE\n  anomaly = true\nGROUP BY\n  city,\n  temperature,\n  wind_speed,\n  humidity,\n  pressure\nORDER BY\n  anomaly_count DESC;"
    }
   ]
  },
  {
   "title": "Events, Avg Lag & Anomalies (30-min timestamp-based aggregation) - last 3 hours",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  to_timestamp(\n    FLOOR(timestamp / (30 * 60)) * (30 * 60)\n  ) AS time,\n  COUNT(*) AS event_count,\n  AVG(processing_time - event_time) AS avg_lag_seconds,\n  COUNT(*) FILTER (WHERE anomaly = true) AS anomaly_count\nFROM\n  weather_data\nWHERE\n  to_timestamp(timestamp) > now() - interval '3 hours'\nGROUP BY\n  time\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Summary Metrics: City Count, Anomaly Distribution, Attribute Completeness, and Country Breakdown",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT 'distinct_cities' AS metric, COUNT(DISTINCT city) AS value\nFROM weather_data\n\nUNION ALL\n\nSELECT 'anomaly_true_count', COUNT(*) FROM weather_data WHERE anomaly = true\n\nUNION ALL\n\nSELECT 'anomaly_false_count', COUNT(*) FROM weather_data WHERE anomaly = false\n\nUNION ALL\n\nSELECT \n  'sys_country_' || sys_country AS metric, \n  COUNT(*) AS value\nFROM weather_data\nGROUP BY sys_country\n\nUNION ALL\n\nSELECT 'temperature_count', COUNT(temperature)\nFROM weather_data\n\nUNION ALL\n\nSELECT 'humidity_count', COUNT(humidity)\nFROM weather_data\n\nUNION ALL\n\nSELECT 'pressure_count', COUNT(pressure)\nFROM weather_data\n\nUNION ALL\n\nSELECT 'wind_speed_count', COUNT(wind_speed)\nFROM weather_data\n\nUNION ALL\n\nSELECT 'cloud_coverage_count', COUNT(cloud_coverage)\nFROM weather_data;"
    }
   ]
  },
  {
   "title": "Average Weather Metrics per City (Temperature, Humidity, Pressure, Wind Speed)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  city,\n  AVG(temperature) AS \"average_temperature\",\n  AVG(humidity) AS \"average_humidity\",\n  AVG(pressure) AS \"average_pressure\",\n  AVG(wind_speed) AS \"average_wind_speed\"\nFROM\n  weather_data\nGROUP BY\n  city\nORDER BY\n  city ASC;"
    }
   ]
  },
  {
   "title": "Temperature by city (max Value)",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  city AS \"location\",\n  lat AS \"latitude\",\n  lon AS \"longitude\",\n  max(temperature) AS \"value\"\nFROM\n  weather_data\n  GROUP BY city, lat, lon;"
    }
   ]
  },
  {
   "title": "Average Temperature and Wind Speed per Hour (based on timestamp)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', to_timestamp(timestamp)) AS \"time\",\n  AVG(temperature) AS average_temperature,\n  AVG(wind_speed) AS average_wind_speed\nFROM\n  weather_data\nGROUP BY\n  date_trunc('hour', to_timestamp(timestamp))\nORDER BY\n  \"time\";"
    }
   ]
  }
 ]
}